Q1
function pascal(r, p) {
    return r === 0 || p === 0 || r === p
        ? 1
        : pascal(r-1, p-1) + pascal(r-1, p);
}

pascal(4,2);
pascal(4,3);

// Q2
// draw the tree illustrating the process generated by pascal(4, 3) to compute
// the value in Pascal’s triangle in row 4 and position 3
// recursive due to presence of deferred operations